// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoeJEGXMLYUgbmY9otbTQ78JRjySrezlI',
    appId: '1:241021971924:web:9af17f86b3d0ca20413a41',
    messagingSenderId: '241021971924',
    projectId: 'universe-e48a9',
    authDomain: 'universe-e48a9.firebaseapp.com',
    storageBucket: 'universe-e48a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZMfIOxHdfaDGNgRvJyITEbTB4OrC0eJ8',
    appId: '1:241021971924:android:7cf97f582098d6db413a41',
    messagingSenderId: '241021971924',
    projectId: 'universe-e48a9',
    storageBucket: 'universe-e48a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1S-ES99_Di7XDWsb7GXZ5Vsf2aGqsCwM',
    appId: '1:241021971924:ios:2e732746d63d4cef413a41',
    messagingSenderId: '241021971924',
    projectId: 'universe-e48a9',
    storageBucket: 'universe-e48a9.appspot.com',
    androidClientId: '241021971924-gm6do2r43vgpjl626sn3c7sm2pceob5n.apps.googleusercontent.com',
    iosClientId: '241021971924-3ttunvqcmokajg05eek6phnev0nevksh.apps.googleusercontent.com',
    iosBundleId: 'com.raian.universe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1S-ES99_Di7XDWsb7GXZ5Vsf2aGqsCwM',
    appId: '1:241021971924:ios:e495709eaf2bb6b2413a41',
    messagingSenderId: '241021971924',
    projectId: 'universe-e48a9',
    storageBucket: 'universe-e48a9.appspot.com',
    androidClientId: '241021971924-gm6do2r43vgpjl626sn3c7sm2pceob5n.apps.googleusercontent.com',
    iosClientId: '241021971924-7l0un9dkgcd68vgmi8hbe6cgfk7uqqe4.apps.googleusercontent.com',
    iosBundleId: 'com.raian.universe.RunnerTests',
  );
}
